### ISSUE TITLE
100 km grid squares designation problem

### ISSUE THREAD

**Issue by szlosu** [klakar/LayoutLoader#2]
I've installed the plugin but there is one problem. MGRS grid generates, but letter designations are incorrect. What I should do to make them the same as they are in real?

I've attached some screens:
-Actual MGRS grid in Poland (You can see zones and 100 km squares designations)
-screen from google maps where 4 zones meet themselves 
-screen from qgis where you can see that grid designation are incorrect

I've also attached some screens:
-Actual MGRS grid in Poland (You can see zones and 100 km sqares designations)
-screen from google maps where 4 zones meets themselves 
-screen from qgis where you can see that grid designation are incorrect

Thanks in advance;)

![Poland MGRS](https://user-images.githubusercontent.com/58152072/103442041-d3d65380-4c52-11eb-8d20-f4fefc87a1d7.jpg)

![correct grid](https://user-images.githubusercontent.com/58152072/103442103-873f4800-4c53-11eb-9439-9796300e73e6.jpg)

![qgisscreenshot](https://user-images.githubusercontent.com/58152072/103442292-24e74700-4c55-11eb-9bf9-708f36026a16.jpg)

**Comment by szlosu** [comment]
![maplarger](https://user-images.githubusercontent.com/58152072/103442711-08e5a480-4c59-11eb-8311-3784ee43e423.jpg)

And there You can see it in different scale.

**Comment by klakar** [comment]
I guess you have installed the **LatLonTools**?
That plugin now includes an identically named function (_mgrs_) used in the layouts in this plugin.
For LatLonTools the function use _mgrs(y, x)_ order while the function in this plugin use _mgrs(x, y)_ order.
I will change the layouts in this plugin eventually, but for now you will need to edit the expressions used to generate anything mgrs and reverse the **x,y** order (to **y, x**) manually.

**Comment by szlosu** [comment]
So, without LatLonTools your formulas will work corectly?

**Comment by szlosu** [comment]
Could you give me an exmple of expresions with reversed order of the X and Y? I'm not experienced with python formulas.

**Comment by szlosu** [comment]
Or meybe I should unistall LatLong? But I can't see it in "installed plugins" menu.

**Comment by szlosu** [comment]
I've uninstalled LatLon but layersloader still don't works correctly. Letters have changed but grid is still not as same as it should be.

**Comment by szlosu** [comment]
Letters have changed but there are another problems:

![image](https://user-images.githubusercontent.com/58152072/103482928-08c5e000-4de4-11eb-884d-5c6a2d8727b7.png)
1) I have 4 same letter designations.

![image](https://user-images.githubusercontent.com/58152072/103482970-4b87b800-4de4-11eb-84e0-985977884ef2.png)

2) In real, near "Szydłów" town four different 100 km squares meet themselves. In qgis, they don't.

What should I do with it?

**Comment by szlosu** [comment]
![image](https://user-images.githubusercontent.com/58152072/103808528-66626280-5058-11eb-9542-bf3812d61a3a.png)

I've used your latest MGRS models. Everything was alright util I saved grid in a project. I have also saved scratch layers. Everything is ok, but 1 km grid designations are crossing on the center of map. Do you know how to repair it?

**Comment by klakar** [comment]
That is just the line labels. Disable labelling for the layer and the labels go away.
As for the MGRS letters it is a problem when the mgrs() function I've included in the plugin and the mgrs() function from LatLonTools use different x,y order. I would suggest removing the "mgrs" folder from your QGIS profile and deleting the custom functions from the expression builder. Only use new, updated layouts with the LatLonTools plugin.
